### PR TITLE
[WIP] Customize config permissions

### PR DESCRIPTION
**Pull request by jcii**
Hi Chad,

I'm not done with tests and stuff, but here's a peek at the things I've changed so I can use this at my work. Converting conf file values to be settable from attributes. Please give it a look and see if this is something you'd want to merge into your branch.

-Jimmy

### CODE REVIEW

**Comment by CBarraford** [comment]
it looks pretty good generally. Can the default perms be whatever it was before (`0660`?)

**Comment by CBarraford** [comment]
I just ask so that people upgrading from previous versions won't get a surprised by it.

**Comment by jcii** [comment]
yea definitely. I missed that.

**Comment by CBarraford** [comment]
I updated the title with a `[WIP]` (work in progress).

Also, i've made a bunch of linting changes that you'll need to merge in

**Comment by jcii** [comment]
Ok cool. I'm away with the family. I'll be back at the puter Sunday.

**Comment by cbarraford** [comment]
@jcii hey, whats the status of this PR? My understanding is that there are some more changes you're working on. Is that true?

**Comment by jcii** [comment]
Howdy,

I was laid off and dont have access to the project i was working on....so
go ahead without me.

**Pull request closed without merging**
