### PR TITLE
Testing updates and fix up OS support for Debian and RHEL

### PR DESCRIPTION
**Pull request by shortdudey123**
- Fix FC and Rubocop offenses
- Add chefspec
- Add support for Debian
- Fix RHEL family support

### CODE REVIEW

**Comment by shortdudey123** [comment]
@CBarraford let me know your thoughts.  I made quite a few changes, improvements, and additions.
I kept all of the commits so that its easier to follow.  If you want me to squash it a bit, let me know and thats not a problem

**Review by cbarraford — APPROVED** [review]
Great work @shortdudey123. For future reference, i'd prefer breaking something like this into smaller PRs, but this is great stuff. Thanks for contributing.

**Comment by cbarraford** [comment]
@shortdudey123 i've released a new version (`2.1.0`) with your changes. Thanks again.

**Comment by shortdudey123** [comment]
Will do and thanks!

**Pull request merged**
